### ISSUE TITLE
敢问阁下哪来的勇气？

### ISSUE THREAD

**Issue by fyy99** [shirakun/Tieba-Cloud-Sign#11]
你是对云签事业做了多大贡献？去版权是么
去了版权还把自己名字加上？你是程序作者？
     
> 由于原作者在版权方面**过分的**加入了超链接以及meta信息，所以本程序由しら様在2016-02-07进行了版权去除。

来来来，你告诉我，谁过分？

**Comment by shirakun** [comment]
我并未在页头和页脚加入我的链接，”关于“菜单里面的链接也写明了去除方法，若你觉得不妥，提交一个去除链接的即可，另外 “关于”菜单里的链接我在近期也会去除。
我使用wordpress/roundcube/rainloop等程序并不会去除版权等东西，因为它们的链接并不会写到每个页面

**Comment by 96dl** [comment]
来来来，你先别说别的，我就问问你有什么资格去除云签版权，你是开发者？还是协助开发者？都不是？那你有什么资格去除？版权写在每个页面怎么了？碍你眼你可以不用啊，没人逼你用，你怎么不换位思考想想，如果这程序你写的，别人拿去给你删了版权再加点自己的版权再到处发，你自己是什么感想？你不尊重别人劳动成果，别人为何尊重你？

**Comment by fyy99** [comment]
@shirakun
首先，我不否认原程序中版权链接较多，但这并不是你去除它们的合理理由。
既然你打算使用该程序，你就必须**全部接受**协议中的内容，这是基本的**原则**、是**开源精神**、是对作者的**尊重**。
----
而你现在不仅去除了版权链接，而且还将去除后的版本发布出来，
你觉得这对得起作者的辛苦付出吗？
----
希望你能够主动停止发布[去版权的版本]，
更多地，你应该向作者@kenvix 道歉
----
如果你就是看着不顺眼，你可以购买商业授权，或是**不用这个程序**
