### ISSUE TITLE
几句话送给您哦。

### ISSUE THREAD

**Issue by kirainmoe** [shirakun/Tieba-Cloud-Sign#6]
我作为一个LLer，对于LLer中有您这种人我表示深深的佩服。
对您装的逼我给82分，剩下的18分以666的形式送出。
以版权太多去掉了版权这理由我给您满分，作业太多你是不是也要把作业烧掉啊？
最后，送您一句话如何：
> # 阁下何不随风起，扶摇直上九万里？#

我平生最讨厌只会改个名字来装逼，除此之外什么都不会的人。以上。

**Comment by tyan-boot** [comment]
老师留的作业太多了，满书包都是作业，看着烦，我就去掉了，然后换成了我的课♂外♂书♂了。
